import type { Official } from "./types";

/**
 * Leadership roster for public Officials page and homepage preview.
 * Executives 1–3 use names published on draft.cjacanada.ca; remaining seats
 * are explicit placeholders until CJA publishes names.
 * Bio / term fields feed the expandable person cards on /officials.
 */
export const officials: Official[] = [
  // —— Directors (3 placeholders) ——
  {
    id: "dir-01",
    fullName: "Director 1",
    designation: "Director",
    category: "Directors",
    displayOrder: 1,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Director",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "dir-02",
    fullName: "Director 2",
    designation: "Director",
    category: "Directors",
    displayOrder: 2,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Director",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "dir-03",
    fullName: "Director 3",
    designation: "Director",
    category: "Directors",
    displayOrder: 3,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Director",
    termStart: "TBD",
    termEnd: "TBD",
  },

  // —— Executives (3 real + 6 placeholders) ——
  {
    id: "ex-01",
    fullName: "Sumit Rana",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 1,
    status: "active",
    shortBio:
      "Serves on the CJA executive team. Based in Mississauga. Contact publicly listed on draft.cjacanada.ca: 437-259-4035.",
    occupation: "Mississauga",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
    photoUrl: "/images/members/sumitr.jpg",
  },
  {
    id: "ex-02",
    fullName: "Subhash Punia",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 2,
    status: "active",
    shortBio:
      "Serves on the CJA executive team. Based in Brampton. Contact publicly listed on draft.cjacanada.ca: 416-569-3442.",
    occupation: "Brampton",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
    photoUrl: "/images/members/subhashp.jpg",
  },
  {
    id: "ex-03",
    fullName: "Virendra Sheoran",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 3,
    status: "active",
    shortBio:
      "Serves on the CJA executive team. Based in Mississauga. Contact publicly listed on draft.cjacanada.ca: 647-231-4561.",
    occupation: "Mississauga",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
    photoUrl: "/images/members/virenders.jpg",
  },
  {
    id: "ex-04",
    fullName: "Executive 4",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 4,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "ex-05",
    fullName: "Executive 5",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 5,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "ex-06",
    fullName: "Executive 6",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 6,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "ex-07",
    fullName: "Executive 7",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 7,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "ex-08",
    fullName: "Executive 8",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 8,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },
  {
    id: "ex-09",
    fullName: "Executive 9",
    designation: "Executive Member",
    category: "Executives",
    displayOrder: 9,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Selected as Executive Member",
    termStart: "TBD",
    termEnd: "TBD",
  },

  // —— Corporate Secretary (1 placeholder) ——
  {
    id: "cs-01",
    fullName: "Corporate Secretary",
    designation: "Corporate Secretary",
    category: "Corporate Secretary",
    displayOrder: 1,
    status: "active",
    shortBio: "Bio coming soon.",
    occupation: "TBD",
    appointedAs: "Appointed as Corporate Secretary",
    termStart: "TBD",
    termEnd: "TBD",
  },
];

/** Preferred category display order when present; unknown categories follow alphabetically. */
export const categoryOrder = [
  "Directors",
  "Executives",
  "Corporate Secretary",
] as const;
