import type { Official } from "./types";

/**
 * Sample leadership data — counts are NOT hard-coded in UI.
 * Admins (later CMS) can add/remove/reorder by editing this module or replacing it with D1.
 */
export const officials: Official[] = [
  // Executives (sample 9)
  {
    id: "ex-01",
    fullName: "Sample President",
    designation: "President",
    category: "Executives",
    displayOrder: 1,
    status: "active",
    shortBio: "Leads CJA strategic direction and community outreach across Canada.",
    termStart: "2025-01-01",
    joinedAt: "2020-03-15",
  },
  {
    id: "ex-02",
    fullName: "Sample Vice President",
    designation: "Vice President",
    category: "Executives",
    displayOrder: 2,
    status: "active",
    shortBio: "Supports programs, events, and member engagement.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-03",
    fullName: "Sample General Secretary",
    designation: "General Secretary",
    category: "Executives",
    displayOrder: 3,
    status: "active",
    shortBio: "Coordinates meetings, records, and official correspondence.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-04",
    fullName: "Sample Treasurer",
    designation: "Treasurer",
    category: "Executives",
    displayOrder: 4,
    status: "active",
    shortBio: "Oversees association finances and reporting (CAD).",
    termStart: "2025-01-01",
  },
  {
    id: "ex-05",
    fullName: "Sample Cultural Secretary",
    designation: "Cultural Secretary",
    category: "Executives",
    displayOrder: 5,
    status: "active",
    shortBio: "Plans festivals, heritage programs, and youth cultural activities.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-06",
    fullName: "Sample Sports Secretary",
    designation: "Sports Secretary",
    category: "Executives",
    displayOrder: 6,
    status: "active",
    shortBio: "Organizes kabaddi, volleyball, and community sports meets.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-07",
    fullName: "Sample Youth Coordinator",
    designation: "Youth Coordinator",
    category: "Executives",
    displayOrder: 7,
    status: "active",
    shortBio: "Connects next-generation members with mentors and events.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-08",
    fullName: "Sample Media Secretary",
    designation: "Media Secretary",
    category: "Executives",
    displayOrder: 8,
    status: "active",
    shortBio: "Manages public communications and social channels.",
    termStart: "2025-01-01",
  },
  {
    id: "ex-09",
    fullName: "Sample Membership Secretary",
    designation: "Membership Secretary",
    category: "Executives",
    displayOrder: 9,
    status: "active",
    shortBio: "Supports membership onboarding and renewals.",
    termStart: "2025-01-01",
  },
  // Directors (sample 3)
  {
    id: "dir-01",
    fullName: "Sample Director (Ontario)",
    designation: "Director",
    category: "Directors",
    displayOrder: 1,
    status: "active",
    shortBio: "Regional liaison for Ontario chapter activities.",
    termStart: "2025-01-01",
  },
  {
    id: "dir-02",
    fullName: "Sample Director (Alberta)",
    designation: "Director",
    category: "Directors",
    displayOrder: 2,
    status: "active",
    shortBio: "Regional liaison for Alberta chapter activities.",
    termStart: "2025-01-01",
  },
  {
    id: "dir-03",
    fullName: "Sample Director (British Columbia)",
    designation: "Director",
    category: "Directors",
    displayOrder: 3,
    status: "active",
    shortBio: "Regional liaison for B.C. chapter activities.",
    termStart: "2025-01-01",
  },
  // Corporate Secretary (sample 1)
  {
    id: "cs-01",
    fullName: "Sample Corporate Secretary",
    designation: "Corporate Secretary",
    category: "Corporate Secretary",
    displayOrder: 1,
    status: "active",
    shortBio: "Governance, filings, and board support.",
    termStart: "2025-01-01",
  },
  // Archived — Past Executives samples
  {
    id: "arch-01",
    fullName: "Sample Past President A",
    designation: "President",
    category: "Executives",
    displayOrder: 1,
    status: "archived",
    tenureLabel: "2022–2025",
    termStart: "2022-01-01",
    termEnd: "2024-12-31",
    shortBio: "Led community expansion during the 2022–2025 term.",
  },
  {
    id: "arch-02",
    fullName: "Sample Past Vice President A",
    designation: "Vice President",
    category: "Executives",
    displayOrder: 2,
    status: "archived",
    tenureLabel: "2022–2025",
    termStart: "2022-01-01",
    termEnd: "2024-12-31",
  },
  {
    id: "arch-03",
    fullName: "Sample Past Treasurer A",
    designation: "Treasurer",
    category: "Executives",
    displayOrder: 3,
    status: "archived",
    tenureLabel: "2022–2025",
    termStart: "2022-01-01",
    termEnd: "2024-12-31",
  },
  {
    id: "arch-04",
    fullName: "Sample Past President B",
    designation: "President",
    category: "Executives",
    displayOrder: 1,
    status: "archived",
    tenureLabel: "2019–2022",
    termStart: "2019-01-01",
    termEnd: "2021-12-31",
  },
  {
    id: "arch-05",
    fullName: "Sample Past Secretary B",
    designation: "General Secretary",
    category: "Executives",
    displayOrder: 2,
    status: "archived",
    tenureLabel: "2019–2022",
    termStart: "2019-01-01",
    termEnd: "2021-12-31",
  },
];

/** Preferred category display order when present; unknown categories follow alphabetically. */
export const categoryOrder = [
  "Executives",
  "Directors",
  "Corporate Secretary",
] as const;
